//! High-level semantic editor actions and translation from raw input.
//! Phase 1 Task 9.4–9.5: Introduce Action abstraction.

use core_events::KeyEvent;
use core_state::Mode;

mod key_translator;
use key_translator::KeyTranslator;

#[doc(hidden)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// Pre-Phase 4 operator kind scaffold. Variants are doc-hidden and not yet
/// produced by key translation. Introduced in Refactor R3 Step 4 to enable
/// forward-compatible wiring of operator/count logic without semantic changes.
pub enum OperatorKind {
    Delete,
    Yank,
    Change,
}

/// Observer hook (Refactor R1 Step 8): allows external components (macro recorder, analytics,
/// future plugin host) to observe Actions as they are translated and/or dispatched without
/// mutating editor state. Breadth-first: only pre-dispatch hook provided now.
///
/// Observers MUST be cheap and non-blocking; heavy work should be offloaded asynchronously.
pub trait ActionObserver: Send + Sync {
    /// Called immediately before an Action is dispatched (state not yet mutated).
    fn on_action(&self, action: &Action);
}

impl<T: ActionObserver + ?Sized> ActionObserver for &T {
    fn on_action(&self, action: &Action) {
        (**self).on_action(action)
    }
}

#[derive(Debug, Clone)]
pub enum Action {
    Motion(MotionKind),
    Edit(EditKind),
    ModeChange(ModeChange),
    Undo,
    Redo,
    #[doc(hidden)]
    /// Begin an operator sequence (awaiting a motion). Not yet generated by key
    /// translation (Refactor R3 Step 4 scaffold).
    BeginOperator(OperatorKind),
    #[doc(hidden)]
    /// Apply an operator to a motion with an optional count already resolved.
    /// Not yet generated; future Phase 4 translator logic will emit.
    ApplyOperator {
        op: OperatorKind,
        motion: MotionKind,
        count: u32,
    },
    // Command line actions (Task 7.1 Action Enum Refinement)
    CommandStart,           // begin command line (inserts leading ':')
    CommandChar(char),      // insert character into command buffer
    CommandBackspace,       // remove last character or cancel if only ':'
    CommandCancel,          // abort command (Esc)
    CommandExecute(String), // execute full buffer (still includes leading ':')
    Quit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MotionKind {
    Left,
    Right,
    Up,
    Down,
    LineStart,
    LineEnd,
    WordForward,
    WordBackward,
    /// Half page down (Phase 2 Step 11)
    PageHalfDown,
    /// Half page up (Phase 2 Step 11)
    PageHalfUp,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EditKind {
    InsertGrapheme(String),
    InsertNewline,
    Backspace,
    DeleteUnder,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModeChange {
    EnterInsert,
    LeaveInsert,
}

/// Pure translation from a key event + editor mode + current command buffer into an Action.
/// This does NOT mutate state and is safe to unit test in isolation.
/// Stateful key translation wrapper.
///
/// This preserves the existing public API while internally routing through a
/// singleton `KeyTranslator` instance that will (in future steps) accumulate
/// count prefixes and operator state. For now semantics are unchanged.
pub fn translate_key(mode: Mode, pending_command: &str, key: &KeyEvent) -> Option<Action> {
    use std::cell::RefCell;
    thread_local! {
        static TRANSLATOR: RefCell<KeyTranslator> = RefCell::new(KeyTranslator::new());
    }
    TRANSLATOR.with(|t| t.borrow_mut().translate(mode, pending_command, key))
}

pub mod dispatcher;
pub mod io_ops; // Refactor R2 Step 5: file IO helpers

#[cfg(test)]
mod tests {
    use super::*;
    use core_events::{KeyCode, KeyEvent, KeyModifiers};
    fn kc(c: char) -> KeyEvent {
        KeyEvent {
            code: KeyCode::Char(c),
            mods: KeyModifiers::empty(),
        }
    }

    #[test]
    fn normal_mode_motion() {
        assert!(matches!(
            translate_key(Mode::Normal, "", &kc('h')),
            Some(Action::Motion(MotionKind::Left))
        ));
        assert!(translate_key(Mode::Normal, "", &kc('z')).is_none());
    }

    #[test]
    fn insert_mode_inserts() {
        assert!(
            matches!(translate_key(Mode::Insert, "", &kc('a')), Some(Action::Edit(EditKind::InsertGrapheme(ref s))) if s=="a")
        );
    }

    #[test]
    fn command_sequence_translation() {
        // start
        let start = translate_key(Mode::Normal, "", &kc(':'));
        assert!(matches!(start, Some(Action::CommandStart)));
        // after ':' pending buffer would be ':'; simulate adding 'q'
        let q = translate_key(Mode::Normal, ":", &kc('q'));
        assert!(matches!(q, Some(Action::CommandChar('q'))));
        // Enter executes
        let enter = translate_key(
            Mode::Normal,
            ":q",
            &KeyEvent {
                code: KeyCode::Enter,
                mods: KeyModifiers::empty(),
            },
        );
        assert!(matches!(enter, Some(Action::CommandExecute(ref s)) if s==":q"));
        // Esc cancels when active
        let esc = translate_key(
            Mode::Normal,
            ":q",
            &KeyEvent {
                code: KeyCode::Esc,
                mods: KeyModifiers::empty(),
            },
        );
        assert!(matches!(esc, Some(Action::CommandCancel)));
        // Backspace
        let bs = translate_key(
            Mode::Normal,
            ":q",
            &KeyEvent {
                code: KeyCode::Backspace,
                mods: KeyModifiers::empty(),
            },
        );
        assert!(matches!(bs, Some(Action::CommandBackspace)));
    }

    #[test]
    fn ctrl_r_maps_to_redo() {
        use core_events::{KeyCode, KeyEvent, KeyModifiers};
        let evt = KeyEvent {
            code: KeyCode::Char('r'),
            mods: KeyModifiers::CTRL,
        };
        let act = translate_key(Mode::Normal, "", &evt);
        assert!(
            matches!(act, Some(Action::Redo)),
            "Ctrl-R should map to Redo action"
        );
        // Ensure plain 'r' (no ctrl) is currently unbound (reserved for future replace semantics)
        let plain = KeyEvent {
            code: KeyCode::Char('r'),
            mods: KeyModifiers::empty(),
        };
        assert!(translate_key(Mode::Normal, "", &plain).is_none());
    }

    #[test]
    fn operator_variants_constructible() {
        // Ensure the new operator-related Action variants remain reachable and compile.
        let _op = OperatorKind::Delete;
        let begin = Action::BeginOperator(_op);
        match begin {
            Action::BeginOperator(OperatorKind::Delete) => {}
            _ => panic!("Unexpected variant"),
        }
        let apply = Action::ApplyOperator {
            op: OperatorKind::Yank,
            motion: MotionKind::Left,
            count: 2,
        };
        if let Action::ApplyOperator { op, motion, count } = apply {
            assert_eq!(op, OperatorKind::Yank);
            assert_eq!(motion, MotionKind::Left);
            assert_eq!(count, 2);
        } else {
            panic!("ApplyOperator pattern mismatch");
        }
    }

    // Removed: colon_variant_translation test (Refactor R2 Step 8) – KeyCode::Colon eliminated; ':' represented solely via KeyCode::Char(':').
}
